language: java
jdk: openjdk8
script:
  - jdk_switcher use openjdk8
  - mvn clean package
cache:
  directories:
  - "$HOME/.m2"
notifications:
   slack: sunbird-ci:UegIg4Bf86V3HcXAB2uXNLGI
   on_success: never
   on_failure: always
   email:
     recipients:
      - manzarul.haque@tarento.com
      - amit.kumar@tarento.com
      - vinayab@ilimi.in
     on_success: never
     on_failure: always
git:
  submodules: false
before_install:
  - git submodule update --init --recursive --remote
