## This section has mandatory variables
## You must provide a value for these
## If you don't provide a value for these variables, the chart installation will not proceed

## The domain name or Public IP address
## The domain name should start with http or https
## For example https://example.com
domain: "https://abc.com"

## Can be one of - azure, aws, gcloud
cloud_service_provider: "aws"

## Public storage bucket details
cloud_public_storage_accountname: "public"
cloud_public_storage_secret: "publicsecret"

## Private storage bucket details
cloud_private_storage_accountname: "private"
cloud_private_storage_secret: "privatesecret"


## This section has optional variables
## It is strongly recommended to provide a value for these
## If you don't provide a value for these variables, they will default to empty values
## If these variables are empty, some features on the application might not work as expected 
google_captcha_mobile_private_key: ""
google_captcha_private_key: ""
sunbird_mail_server_from_email: ""
sunbird_mail_server_host: ""
sunbird_mail_server_password: ""
sunbird_mail_server_port: ""
sunbird_mail_server_username: ""
sunbird_msg_91_auth: ""
sunbird_msg_sender: ""
sunbird_url_shortner_access_token: ""


## The merge domain name or Public IP address
## The merge domain name should start with http or https
## For example https://merge.example.com
merge_domain: ""

user-access-keys:
  user_access_private_keys:
    accessv1_key1: |
      -----BEGIN PRIVATE KEY-----
      MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC5GDQK2PSrnojv
      g3vYBuJuHslvgv+IdqtnFhMEwQrfJJd4PNkxATR69/OO2OO4xd8tC+bQYkPcImO0
      Y3ynvsVwbJ2che2dS6RvsZh5Es7dpcf7UVp9AQb4QPTvGDYagrekf3cpdy3CoeZm
      lb1jOmJKP6YS4PIqmeO4dfsz0p2rNraeg42Dpgt6wcievSvyXIf6QqDwCpp/HnK4
      Kso2yL9XSUE87Khhb6itbAos9TnRpraVZYho2WuDTXQYfYZHEr8EzX1mS8dQhJTr
      N6Nl7PVteVfxFqQR41a1WB/w5Lx3iYawhmuI1eSuAmZT3PoeRTXFalJlyNJb74je
      DgOYCYiTAgMBAAECggEAM4DkmlAcZNTMTblMcKQZxYKTko/lAtfigeDGkgAVQlow
      O6jS1qv7KmxsPUdktjl5DFPPehSdxVdcXwl/2j1fOxU+Fhu+LpKpwtqsDqSJI2vJ
      5ciRYU8z3UhV32HhTCcran59bfBXr1zVe54XANFyIC7tyzsEp44Cq4VIzPbCIK2z
      oSYul4ydJmuJ6THsDNdWSWGyE/1iNGD94JnlIuQZ+0r/GXRf9BDLnNPKVfj2lcO5
      OuNTZE5jkrgSC+TXoHV7m32V/4XQRpJZ2aAr2LrBCW4iy+3/IbgFmKr6HfQIoHWY
      K9Vgk8wdcBnfcTdoCHVE42fzHqIom/R8STRFVNHswQKBgQDdy3AcFhW9TFRw0Sa+
      JOG2qXgKLQWyKxaH5jfdGsQw0nUT08fgTlDCxcC64ByIzmc02l4kB23a6XzViR4v
      /K3519A5iKfC1alfMFcDokDjPRkdiZ5hHaPfWBrLp+KL0GtoAogR6qyE9i47XFqQ
      VC/zAPoRoBjwFFO6RGkTkuwcCQKBgQDVo9N9I7vtG2G2+LcXoCxUFcZw8ogpYmrT
      m1DKAMQxid5rc/0P1OSdudtjYMpdXPKXeyztHhFxBwlvZG5kiPz/yRO0jHJTQbZP
      yP/hZOf2Dcwmf0RyIFbynBD8Vkla/ChjDbZM6Sv+6GkXU4DvjAQdh1Um5923EZML
      OKkraggeuwKBgQDVXivI6ToatL6bFaomzAZUGi4/49YR87+mF0RwsZpBuYUmANvN
      Hqo05dcmMAljVuUUhGqCUJ9PNMWCC3n+AiBANWy8nIl/NtrMlw1ukn3H3fQ2ZTj3
      BnOqnfCRMT4Q8P0SvzS1v8Qd2VLailsZc9P4+1yW7iRvea6eh8dqLDJ2OQKBgCbO
      Gxwf4YKv9o/FnXwtG+AqFGFvrEvYFI9bJtGKUhitcjkSWGUHxn7fw3nJmvhaabYa
      KY7oZ0KghJY3J9YbC9lqLKoe2KVGylazq8bFDV0kJHDZrRUNyr1Gm8853RkptCxJ
      0VMnB1bF4FDcWg8o35Z9fnoSo7Mc/hiLsi6wk8kBAoGAVaojV+zrC07VDcLKNtsh
      R+87iJCNldFV1X2rfPYFMLDWyLubd0g1v8ulYlk3KRv2MNYftaNHT4PXNSZuhfJy
      mg13rZDoFKFB5DRpfv6ybZIaGxrZ9R+2lV2pFCgFuTExtAufN/JeXM6hNzdAzRgK
      dhMts6drDP0QTO0yK99dPa4=
      -----END PRIVATE KEY-----
    accessv1_key2: |
      -----BEGIN PRIVATE KEY-----
      MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDoxlV1cR2IXQtj
      3kEpgnTySHWncmdtBOeNKVBQetZ14CSqVadLHsK+sZgeRm0zY6GURn6IxWaxUbhG
      sHhc6WKKOhKFOOgjv38E7eDq6llnH2hOA8Lypu63Ijdbc2ifYCpuyfwRT9vEpbFo
      vE1SqSZmplkOh1+zFjzf2TypZcdLLRABkGd/0ZelOG9qx7bM2th8nOcH/uVsFO5R
      YELvRkEUUegNvIUq6MtVRH4A1hE3a5EYtPQD9KV8VcyMVET883MgL5tSI8Mhu2nL
      mNY6Q7Stnp6VemuCCe5hd9SRnfr0ytV0K9JaA4zAS4isEHwcP97oyhNs6IhL64iw
      7FQwshxnAgMBAAECggEBAIq/bcELI6dcjqWAnSa49CxWtIqSzsNU4RBrR8ww7BRm
      /nPpikZkl4BDK4EgSYcQJAfV3SZ5Q7T+GPFJzvTSyEHMS63NNdHZG0U85YwhFBk7
      x1h5NYKdrjzK0GRabkpRb/mJvA41o7GbchwT4aMb4B/fl8XpO0nsP2zOeDIg0KIl
      nxiZToaZocwJh4IkfYMnOhSp617ZBbLb25cdRAIEQaGLRuoqibfmB+cBMmQUGFNB
      O9/efJLVTAWk5NvmOWMZ2Wgs6cjIWZPVDXXbAzz+XWQqi4+6He3NGaJ+vq2NdXGc
      hw3V8BwJGsh9/3usoc2lS9QXDkX771N7WFzmOw3u/EECgYEA9P+cUJNTsvuy0RJC
      ZhewTidY15WkwxBPoUqmTOnfFEMw/DO4jC6JWXFb45lANuooFiQwb8svM6Y+o6hP
      NkPaxt426fEU0F4beBid1vUrOk/4a6SRFUdwPzDaDUwc2+Wwo0QxNlXG6mKPtC12
      dnOtF139edQ24uNdi6oegR2qsu0CgYEA8zo0bEZ0gZdBcMNJtVEoQHAv4DSDGieL
      HghLKaqLsVBWFDysV4w7y8Tqy8GPRUG4MCKIa1zhjY0AY92afdvwYStVhyNj+BWT
      qvTTTYsFvvnUO0MUV5ewwX1QcPLns27SGteN/p5PrEOsJ5R9NDLUJWCGOk3QYscd
      dI7cWNcXfiMCgYBpDt8x8is3GhWw75qHeusAaIEBWUsg1nK/IGq1mqgtYS61R1yA
      yEffkeusaoANzFVKQVR/6+oexNAhj7//7hL3qjx0Dww02dX/ptawYcuaosZNKnGI
      ZWztu/4VK6lIZnNbX5eWzCuTQJaM1d3xp2L3HTffsS+kFYl8pYOVLGqRdQKBgEH0
      F4EAvdjiFfmoytTi0+JdSW4nbyFpdZzILPF4cHa9TQohxa3btd80X2Ku8tWZ04Mh
      6hIK1pKWmHN8BMd6Gz2ODZweaZ4845To3F9bgkxd3EHRl7OEy4Y8H9Lw2wlZ1Jk4
      uCVB8mLI2ubEqgq8ebBE80DeFtKiIYeYsYFZmeI3AoGBAKUWA7KqJ+Gw5QIbJ680
      bZqKZliuCzI4HkXeNNFYv9+8ec+P6prbfP6WlAsjLsPVJj5gV1A/55syhvPzfSXw
      GAcMqQqWTYIyoLJ+idyitJVuFmXi/eAaNDIh001Itz8R6uPWIR/KqIJUagc8ZzcS
      S/euzu2m6qX8poTQAo+NoUp2
      -----END PRIVATE KEY-----
  user_access_public_keys:
    accessv1_key1: |
      -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuRg0Ctj0q56I74N72Abi
      bh7Jb4L/iHarZxYTBMEK3ySXeDzZMQE0evfzjtjjuMXfLQvm0GJD3CJjtGN8p77F
      cGydnIXtnUukb7GYeRLO3aXH+1FafQEG+ED07xg2GoK3pH93KXctwqHmZpW9Yzpi
      Sj+mEuDyKpnjuHX7M9Kdqza2noONg6YLesHInr0r8lyH+kKg8Aqafx5yuCrKNsi/
      V0lBPOyoYW+orWwKLPU50aa2lWWIaNlrg010GH2GRxK/BM19ZkvHUISU6zejZez1
      bXlX8RakEeNWtVgf8OS8d4mGsIZriNXkrgJmU9z6HkU1xWpSZcjSW++I3g4DmAmI
      kwIDAQAB
      -----END PUBLIC KEY-----
    accessv1_key2: |
      -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA6MZVdXEdiF0LY95BKYJ0
      8kh1p3JnbQTnjSlQUHrWdeAkqlWnSx7CvrGYHkZtM2OhlEZ+iMVmsVG4RrB4XOli
      ijoShTjoI79/BO3g6upZZx9oTgPC8qbutyI3W3Non2Aqbsn8EU/bxKWxaLxNUqkm
      ZqZZDodfsxY839k8qWXHSy0QAZBnf9GXpThvase2zNrYfJznB/7lbBTuUWBC70ZB
      FFHoDbyFKujLVUR+ANYRN2uRGLT0A/SlfFXMjFRE/PNzIC+bUiPDIbtpy5jWOkO0
      rZ6elXprggnuYXfUkZ369MrVdCvSWgOMwEuIrBB8HD/e6MoTbOiIS+uIsOxUMLIc
      ZwIDAQAB
      -----END PUBLIC KEY-----  

common-opa-policies:
  user-access-keys:
    user_access_private_keys:
      accessv1_key1: |
        -----BEGIN PRIVATE KEY-----
        MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC5GDQK2PSrnojv
        g3vYBuJuHslvgv+IdqtnFhMEwQrfJJd4PNkxATR69/OO2OO4xd8tC+bQYkPcImO0
        Y3ynvsVwbJ2che2dS6RvsZh5Es7dpcf7UVp9AQb4QPTvGDYagrekf3cpdy3CoeZm
        lb1jOmJKP6YS4PIqmeO4dfsz0p2rNraeg42Dpgt6wcievSvyXIf6QqDwCpp/HnK4
        Kso2yL9XSUE87Khhb6itbAos9TnRpraVZYho2WuDTXQYfYZHEr8EzX1mS8dQhJTr
        N6Nl7PVteVfxFqQR41a1WB/w5Lx3iYawhmuI1eSuAmZT3PoeRTXFalJlyNJb74je
        DgOYCYiTAgMBAAECggEAM4DkmlAcZNTMTblMcKQZxYKTko/lAtfigeDGkgAVQlow
        O6jS1qv7KmxsPUdktjl5DFPPehSdxVdcXwl/2j1fOxU+Fhu+LpKpwtqsDqSJI2vJ
        5ciRYU8z3UhV32HhTCcran59bfBXr1zVe54XANFyIC7tyzsEp44Cq4VIzPbCIK2z
        oSYul4ydJmuJ6THsDNdWSWGyE/1iNGD94JnlIuQZ+0r/GXRf9BDLnNPKVfj2lcO5
        OuNTZE5jkrgSC+TXoHV7m32V/4XQRpJZ2aAr2LrBCW4iy+3/IbgFmKr6HfQIoHWY
        K9Vgk8wdcBnfcTdoCHVE42fzHqIom/R8STRFVNHswQKBgQDdy3AcFhW9TFRw0Sa+
        JOG2qXgKLQWyKxaH5jfdGsQw0nUT08fgTlDCxcC64ByIzmc02l4kB23a6XzViR4v
        /K3519A5iKfC1alfMFcDokDjPRkdiZ5hHaPfWBrLp+KL0GtoAogR6qyE9i47XFqQ
        VC/zAPoRoBjwFFO6RGkTkuwcCQKBgQDVo9N9I7vtG2G2+LcXoCxUFcZw8ogpYmrT
        m1DKAMQxid5rc/0P1OSdudtjYMpdXPKXeyztHhFxBwlvZG5kiPz/yRO0jHJTQbZP
        yP/hZOf2Dcwmf0RyIFbynBD8Vkla/ChjDbZM6Sv+6GkXU4DvjAQdh1Um5923EZML
        OKkraggeuwKBgQDVXivI6ToatL6bFaomzAZUGi4/49YR87+mF0RwsZpBuYUmANvN
        Hqo05dcmMAljVuUUhGqCUJ9PNMWCC3n+AiBANWy8nIl/NtrMlw1ukn3H3fQ2ZTj3
        BnOqnfCRMT4Q8P0SvzS1v8Qd2VLailsZc9P4+1yW7iRvea6eh8dqLDJ2OQKBgCbO
        Gxwf4YKv9o/FnXwtG+AqFGFvrEvYFI9bJtGKUhitcjkSWGUHxn7fw3nJmvhaabYa
        KY7oZ0KghJY3J9YbC9lqLKoe2KVGylazq8bFDV0kJHDZrRUNyr1Gm8853RkptCxJ
        0VMnB1bF4FDcWg8o35Z9fnoSo7Mc/hiLsi6wk8kBAoGAVaojV+zrC07VDcLKNtsh
        R+87iJCNldFV1X2rfPYFMLDWyLubd0g1v8ulYlk3KRv2MNYftaNHT4PXNSZuhfJy
        mg13rZDoFKFB5DRpfv6ybZIaGxrZ9R+2lV2pFCgFuTExtAufN/JeXM6hNzdAzRgK
        dhMts6drDP0QTO0yK99dPa4=
        -----END PRIVATE KEY-----
      accessv1_key2: |
        -----BEGIN PRIVATE KEY-----
        MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDoxlV1cR2IXQtj
        3kEpgnTySHWncmdtBOeNKVBQetZ14CSqVadLHsK+sZgeRm0zY6GURn6IxWaxUbhG
        sHhc6WKKOhKFOOgjv38E7eDq6llnH2hOA8Lypu63Ijdbc2ifYCpuyfwRT9vEpbFo
        vE1SqSZmplkOh1+zFjzf2TypZcdLLRABkGd/0ZelOG9qx7bM2th8nOcH/uVsFO5R
        YELvRkEUUegNvIUq6MtVRH4A1hE3a5EYtPQD9KV8VcyMVET883MgL5tSI8Mhu2nL
        mNY6Q7Stnp6VemuCCe5hd9SRnfr0ytV0K9JaA4zAS4isEHwcP97oyhNs6IhL64iw
        7FQwshxnAgMBAAECggEBAIq/bcELI6dcjqWAnSa49CxWtIqSzsNU4RBrR8ww7BRm
        /nPpikZkl4BDK4EgSYcQJAfV3SZ5Q7T+GPFJzvTSyEHMS63NNdHZG0U85YwhFBk7
        x1h5NYKdrjzK0GRabkpRb/mJvA41o7GbchwT4aMb4B/fl8XpO0nsP2zOeDIg0KIl
        nxiZToaZocwJh4IkfYMnOhSp617ZBbLb25cdRAIEQaGLRuoqibfmB+cBMmQUGFNB
        O9/efJLVTAWk5NvmOWMZ2Wgs6cjIWZPVDXXbAzz+XWQqi4+6He3NGaJ+vq2NdXGc
        hw3V8BwJGsh9/3usoc2lS9QXDkX771N7WFzmOw3u/EECgYEA9P+cUJNTsvuy0RJC
        ZhewTidY15WkwxBPoUqmTOnfFEMw/DO4jC6JWXFb45lANuooFiQwb8svM6Y+o6hP
        NkPaxt426fEU0F4beBid1vUrOk/4a6SRFUdwPzDaDUwc2+Wwo0QxNlXG6mKPtC12
        dnOtF139edQ24uNdi6oegR2qsu0CgYEA8zo0bEZ0gZdBcMNJtVEoQHAv4DSDGieL
        HghLKaqLsVBWFDysV4w7y8Tqy8GPRUG4MCKIa1zhjY0AY92afdvwYStVhyNj+BWT
        qvTTTYsFvvnUO0MUV5ewwX1QcPLns27SGteN/p5PrEOsJ5R9NDLUJWCGOk3QYscd
        dI7cWNcXfiMCgYBpDt8x8is3GhWw75qHeusAaIEBWUsg1nK/IGq1mqgtYS61R1yA
        yEffkeusaoANzFVKQVR/6+oexNAhj7//7hL3qjx0Dww02dX/ptawYcuaosZNKnGI
        ZWztu/4VK6lIZnNbX5eWzCuTQJaM1d3xp2L3HTffsS+kFYl8pYOVLGqRdQKBgEH0
        F4EAvdjiFfmoytTi0+JdSW4nbyFpdZzILPF4cHa9TQohxa3btd80X2Ku8tWZ04Mh
        6hIK1pKWmHN8BMd6Gz2ODZweaZ4845To3F9bgkxd3EHRl7OEy4Y8H9Lw2wlZ1Jk4
        uCVB8mLI2ubEqgq8ebBE80DeFtKiIYeYsYFZmeI3AoGBAKUWA7KqJ+Gw5QIbJ680
        bZqKZliuCzI4HkXeNNFYv9+8ec+P6prbfP6WlAsjLsPVJj5gV1A/55syhvPzfSXw
        GAcMqQqWTYIyoLJ+idyitJVuFmXi/eAaNDIh001Itz8R6uPWIR/KqIJUagc8ZzcS
        S/euzu2m6qX8poTQAo+NoUp2
        -----END PRIVATE KEY-----

    user_access_public_keys:
      accessv1_key1: |
        -----BEGIN PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuRg0Ctj0q56I74N72Abi
        bh7Jb4L/iHarZxYTBMEK3ySXeDzZMQE0evfzjtjjuMXfLQvm0GJD3CJjtGN8p77F
        cGydnIXtnUukb7GYeRLO3aXH+1FafQEG+ED07xg2GoK3pH93KXctwqHmZpW9Yzpi
        Sj+mEuDyKpnjuHX7M9Kdqza2noONg6YLesHInr0r8lyH+kKg8Aqafx5yuCrKNsi/
        V0lBPOyoYW+orWwKLPU50aa2lWWIaNlrg010GH2GRxK/BM19ZkvHUISU6zejZez1
        bXlX8RakEeNWtVgf8OS8d4mGsIZriNXkrgJmU9z6HkU1xWpSZcjSW++I3g4DmAmI
        kwIDAQAB
        -----END PUBLIC KEY-----
      accessv1_key2: |
        -----BEGIN PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA6MZVdXEdiF0LY95BKYJ0
        8kh1p3JnbQTnjSlQUHrWdeAkqlWnSx7CvrGYHkZtM2OhlEZ+iMVmsVG4RrB4XOli
        ijoShTjoI79/BO3g6upZZx9oTgPC8qbutyI3W3Non2Aqbsn8EU/bxKWxaLxNUqkm
        ZqZZDodfsxY839k8qWXHSy0QAZBnf9GXpThvase2zNrYfJznB/7lbBTuUWBC70ZB
        FFHoDbyFKujLVUR+ANYRN2uRGLT0A/SlfFXMjFRE/PNzIC+bUiPDIbtpy5jWOkO0
        rZ6elXprggnuYXfUkZ369MrVdCvSWgOMwEuIrBB8HD/e6MoTbOiIS+uIsOxUMLIc
        ZwIDAQAB
        -----END PUBLIC KEY-----  