---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-public
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": "pre-install"
type: Opaque
data:
{{ if .Values.user_access_public_keys }}
{{- range $key, $value := .Values.user_access_public_keys }}
{{ $key | indent 2 }}: {{ $value | b64enc }}
{{- end }}
{{- else -}}
{{- printf "ERROR | %s | Please provide a dictionary of values for \"user_access_public_keys\"" .Chart.Name | fail }}
{{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-private
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": "pre-install"
type: Opaque
data:
{{- if .Values.user_access_private_keys }}
{{- range $key, $value := .Values.user_access_private_keys }}
{{ $key | indent 2 }}: {{ $value | b64enc }}
{{- end }}
{{- else -}}
{{- printf "ERROR | %s | Please provide a dictionary of values for \"user_access_private_keys\"" .Chart.Name | fail }}
{{- end }}